// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtW-KgDGwCWij4LvBZUXh-j1eLb4j2hpg',
    appId: '1:618824063687:web:4609c52d91114487a93ce2',
    messagingSenderId: '618824063687',
    projectId: 'chatapp0123456789',
    authDomain: 'chatapp0123456789.firebaseapp.com',
    databaseURL: 'https://chatapp0123456789-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp0123456789.appspot.com',
    measurementId: 'G-RKL3KC5ND4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_Gw6xlQPAxhdRiQVvj49gs8FKqYI4y0',
    appId: '1:618824063687:android:b747b64d01fb5d69a93ce2',
    messagingSenderId: '618824063687',
    projectId: 'chatapp0123456789',
    databaseURL: 'https://chatapp0123456789-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp0123456789.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8uygAAuCZPVosOjtSiD_vmk1B68g7B3o',
    appId: '1:618824063687:ios:7856d35568f53d76a93ce2',
    messagingSenderId: '618824063687',
    projectId: 'chatapp0123456789',
    databaseURL: 'https://chatapp0123456789-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp0123456789.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8uygAAuCZPVosOjtSiD_vmk1B68g7B3o',
    appId: '1:618824063687:ios:7856d35568f53d76a93ce2',
    messagingSenderId: '618824063687',
    projectId: 'chatapp0123456789',
    databaseURL: 'https://chatapp0123456789-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp0123456789.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtW-KgDGwCWij4LvBZUXh-j1eLb4j2hpg',
    appId: '1:618824063687:web:d3952487f0748282a93ce2',
    messagingSenderId: '618824063687',
    projectId: 'chatapp0123456789',
    authDomain: 'chatapp0123456789.firebaseapp.com',
    databaseURL: 'https://chatapp0123456789-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapp0123456789.appspot.com',
    measurementId: 'G-H3X30PY6EJ',
  );
}
